// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductRepositoryContext))]
    [Migration("20250514144130_AddedSomeFruits")]
    partial class AddedSomeFruits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<bool>("Accessibility")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Accessibility = true,
                            CreationDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yellow fruit",
                            Name = "Banana",
                            OwnerId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Price = 18.1m
                        },
                        new
                        {
                            Id = new Guid("3d490a71-94ce-4d12-9494-5248280c2ce3"),
                            Accessibility = true,
                            CreationDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Red fruit",
                            Name = "Apple",
                            OwnerId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Price = 12.1m
                        },
                        new
                        {
                            Id = new Guid("3d420a70-94ce-3d15-9494-5258280c2ce3"),
                            Accessibility = true,
                            CreationDate = new DateTime(2022, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Orange fruit",
                            Name = "Orange",
                            OwnerId = new Guid("3d290a70-94ce-4d15-9292-5248280c2ce3"),
                            Price = 15.1m
                        },
                        new
                        {
                            Id = new Guid("3d440a70-94ce-4d15-9494-5244240c2ce3"),
                            Accessibility = true,
                            CreationDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Green fruit",
                            Name = "Pear",
                            OwnerId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Price = 100.1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
